### ISSUE TITLE
Would it be possible to just add a screenshoot 

### ISSUE THREAD

**Issue by softyoda** [mantissa-/amaranth-themes#1]
For people like me that discover this theme via github. :)

**Comment by schroef** [comment]
There is one here, https://pablovazquez.art/amaranth/theme/

Otherwise, just download and preview them, it ain't rocket science ;)

**Comment by mantissa-** [comment]
I'll have a look at it! :)

**Comment by mantissa-** [comment]
Done!

**Comment by SanJacobs** [comment]
Heads up, the screenshots are broken now
